# Generated by Django 5.0.4 on 2024-04-30 07:28

import planetarium.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "planetarium",
            "0002_alter_reservation_options_alter_showsession_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="astronomyshow",
            name="image",
            field=models.ImageField(
                null=True, upload_to=planetarium.models.astronomy_show_image_path
            ),
        ),
    ]
